name: alfa_project
description: Demo Alfa bank bussiness project

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  #for svg pictures
  flutter_svg: 0.19.0
  #to pick image from device gallery
  image_picker: 0.6.7+11
  #for network calls api and etc.
  dio: 3.0.9
  #for store local values
  shared_preferences: 0.5.12
  #provider package for state management
  provider: 4.3.2
  #to download and cache images
  cached_network_image: 2.3.0
  #for gesture
  matrix_gesture_detector: 0.1.0
  #for filter photos
  photofilters: 2.0.1
  #to save image to device gallery
  gallery_saver: 2.0.1
  path_provider: 1.6.18
  #file picker
  file_picker: 2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/svg/custom_icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Styrene A LC
      fonts:
        - asset: assets/alfa_fonts/Styrene A LC-Black Italic.otf
        - asset: assets/alfa_fonts/Styrene A LC-Black.otf
        - asset: assets/alfa_fonts/Styrene A LC-Bold Italic.otf
        - asset: assets/alfa_fonts/Styrene A LC-Bold.otf
        - asset: assets/alfa_fonts/Styrene A LC-Light Italic.otf
        - asset: assets/alfa_fonts/Styrene A LC-Light.otf
        - asset: assets/alfa_fonts/Styrene A LC-Medium Italic.otf
        - asset: assets/alfa_fonts/Styrene A LC-Medium.otf
        - asset: assets/alfa_fonts/Styrene A LC-Regular Italic.otf
        - asset: assets/alfa_fonts/Styrene A LC-Regular.otf
        - asset: assets/alfa_fonts/Styrene A LC-Thin Italic.otf
        - asset: assets/alfa_fonts/Styrene A LC-Thin.otf
